# Generated by Django 5.2.14 on 2026-05-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Produto')),
                ('apresentacao', models.CharField(max_length=200, verbose_name='Apresentação / Descrição')),
                ('categoria', models.CharField(choices=[('analgesicos', 'Analgésicos'), ('antibioticos', 'Antibióticos'), ('uso-continuo', 'Uso Contínuo'), ('suplementos', 'Suplementos')], max_length=50, verbose_name='Categoria')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade em Estoque')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='medicamentos/', verbose_name='Fotografia do Produto')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
