# Generated by Django 6.0.5 on 2026-06-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='em_estoque',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='tarja',
            field=models.CharField(choices=[('livre', 'Sem Tarja (Livre de Prescrição)'), ('amarela', 'Tarja Amarela (Genérico)'), ('vermelha_sem_retencao', 'Tarja Vermelha (Sem Retenção da Receita)'), ('vermelha_com_retencao', 'Tarja Vermelha (Com Retenção da Receita)'), ('preta', 'Tarja Preta')], default='livre', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='apresentacao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='categoria',
            field=models.CharField(choices=[('analgesicos', 'Analgésicos'), ('antibioticos', 'Antibióticos'), ('uso-continuo', 'Uso Contínuo'), ('suplementos', 'Suplementos'), ('antidepressivo', 'Antidepressivo'), ('benzodiazepinico', 'Benzodiazepínico'), ('ansiolitico', 'Ansiolítico'), ('psicoestimulante', 'Psicoestimulante'), ('anticonvulsivante', 'Anticonvulsivante'), ('antipsicotico', 'Antipsicótico')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='medicamentos/'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
    ]
